import Head from 'next/head'
import Navigation from "../components/navigation";

export default function Layout({ children }) {
    return (
      <>
        <Head>
            <title>Cruiseport Destinations</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navigation />
        <main>{children}</main>
      </>
    )
  }